import Head from "next/head";
import Image from "next/image";
import homeStyle from "../styles/Home.module.scss";

export default function Home() {
   return (
      <>
         <Head>
            <title>CarePet</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/Logo.png" />
         </Head>
         <main className={homeStyle.main}>
            <section className={homeStyle.section1}>
               <div className={homeStyle.welcome}>
                  Welcome to Care<span className={homeStyle.heroPet}>Pet</span>,
                  Where Pets Are Treated Like Family
               </div>
               <div className={homeStyle.mainContent}>
                  This is your One-Stop Pet Care Destination for Everything You
                  need for Your Pet.
               </div>
               <div className={homeStyle.signUp}>Sign Up Now</div>
            </section>
            <section className={homeStyle.section2}>
               <Image src={"/HeroPic.png"} width="410" height="450"></Image>
            </section>
         </main>

         <article></article>
      </>
   );
}
